name: JIRA validator
on:
  push:
    branches-ignore:
      - main
      - master
      - develop
      - staging
      - dependabot/*
      - translations_*
jobs:
  validate:
    runs-on: [self-hosted, devops-iac]
    steps:
      - uses: Hotmart-Org/actions/jira@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
