name: docker-build

on:
  pull_request:
    branches: [master]
    paths:
    - docker/**

jobs:
  docker-build:
    name: build docker images for the controller and default runner
    runs-on: [self-hosted, devops-iac]
    env:
      REGISTRY: 315120000506.dkr.ecr.us-east-1.amazonaws.com
      DOCKER_BUILDKIT: 1
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up Docker Context for Buildx
      id: buildx-context
      run: |
        docker context create builders
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        endpoint: builders
    - name: Build runner docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        context: .
        file: docker/default-runner/Dockerfile
        tags: ${{ env.REGISTRY }}/github-actions-runner:latest
        cache-from: ${{ env.REGISTRY }}/github-actions-runner:latest
    - name: Build controller docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        context: .
        file: docker/controller/Dockerfile
        tags: ${{ env.REGISTRY }}/actions-runner-controller:latest
        cache-from: ${{ env.REGISTRY }}/actions-runner-controller:latest
